import dayjs from 'dayjs'
import { writeJson } from '../src/lib/data/json'
import type { TripsCollection } from '../src/lib/schemas'

const startDate = dayjs('2025-11-15')

const sampleTrip: TripsCollection = {
  version: 1,
  items: [
    {
      id: 'seed-trip-1',
      title: 'Hanoi to Sapa Adventure',
      destination: 'Sapa, Vietnam',
      startDate: startDate.format('YYYY-MM-DD'),
      endDate: startDate.add(2, 'day').format('YYYY-MM-DD'),
      currency: 'VND',
      createdAt: dayjs().toISOString(),
      updatedAt: dayjs().toISOString(),
      days: [
        { id: 'day-1', tripId: 'seed-trip-1', date: startDate.format('YYYY-MM-DD'), index: 0 },
        {
          id: 'day-2',
          tripId: 'seed-trip-1',
          date: startDate.add(1, 'day').format('YYYY-MM-DD'),
          index: 1,
        },
        {
          id: 'day-3',
          tripId: 'seed-trip-1',
          date: startDate.add(2, 'day').format('YYYY-MM-DD'),
          index: 2,
        },
      ],
      activities: [
        // Day 1 - Hanoi
        {
          id: 'act-1',
          dayId: 'day-1',
          title: 'Breakfast at Banh Mi 25',
          startTime: '08:00',
          endTime: '09:00',
          cost: 50000,
          category: 'Food',
          order: 0,
        },
        {
          id: 'act-2',
          dayId: 'day-1',
          title: 'Explore Hoan Kiem Lake',
          startTime: '09:30',
          endTime: '11:00',
          cost: 0,
          category: 'Sightseeing',
          order: 1,
        },
        {
          id: 'act-3',
          dayId: 'day-1',
          title: 'Lunch at Bun Cha Huong Lien',
          startTime: '12:00',
          endTime: '13:00',
          cost: 80000,
          category: 'Food',
          order: 2,
        },
        {
          id: 'act-4',
          dayId: 'day-1',
          title: 'Visit Temple of Literature',
          startTime: '14:00',
          endTime: '16:00',
          cost: 30000,
          category: 'Sightseeing',
          order: 3,
        },
        {
          id: 'act-5',
          dayId: 'day-1',
          title: 'Evening train to Sapa',
          startTime: '20:00',
          endTime: '21:00',
          cost: 0,
          category: 'Travel',
          notes: 'Boarding at Hanoi Railway Station',
          order: 4,
        },
        // Day 2 - Sapa
        {
          id: 'act-6',
          dayId: 'day-2',
          title: 'Arrive in Lao Cai & Transfer to Sapa',
          startTime: '06:00',
          endTime: '08:00',
          cost: 0,
          category: 'Travel',
          order: 0,
        },
        {
          id: 'act-7',
          dayId: 'day-2',
          title: 'Check-in at Hotel',
          startTime: '08:30',
          endTime: '09:00',
          cost: 0,
          category: 'Accommodation',
          order: 1,
        },
        {
          id: 'act-8',
          dayId: 'day-2',
          title: 'Breakfast at Hotel',
          startTime: '09:00',
          endTime: '10:00',
          cost: 100000,
          category: 'Food',
          order: 2,
        },
        {
          id: 'act-9',
          dayId: 'day-2',
          title: 'Hiking in Cat Cat Village',
          startTime: '10:30',
          endTime: '14:00',
          cost: 70000,
          category: 'Activity',
          order: 3,
        },
        {
          id: 'act-10',
          dayId: 'day-2',
          title: 'Lunch at Local Restaurant',
          startTime: '14:30',
          endTime: '15:30',
          cost: 150000,
          category: 'Food',
          order: 4,
        },
        {
          id: 'act-11',
          dayId: 'day-2',
          title: 'Visit Sapa Market',
          startTime: '16:00',
          endTime: '18:00',
          cost: 0,
          category: 'Shopping',
          order: 5,
        },
        {
          id: 'act-12',
          dayId: 'day-2',
          title: 'Dinner with Mountain View',
          startTime: '19:00',
          endTime: '20:30',
          cost: 200000,
          category: 'Food',
          order: 6,
        },
        // Day 3 - Fansipan & Return
        {
          id: 'act-13',
          dayId: 'day-3',
          title: 'Cable Car to Fansipan Peak',
          startTime: '07:00',
          endTime: '09:00',
          cost: 700000,
          category: 'Activity',
          notes: 'Book tickets in advance',
          order: 0,
        },
        {
          id: 'act-14',
          dayId: 'day-3',
          title: 'Explore Fansipan Summit',
          startTime: '09:00',
          endTime: '11:00',
          cost: 0,
          category: 'Sightseeing',
          order: 1,
        },
        {
          id: 'act-15',
          dayId: 'day-3',
          title: 'Return via Cable Car',
          startTime: '11:30',
          endTime: '13:00',
          cost: 0,
          category: 'Travel',
          order: 2,
        },
        {
          id: 'act-16',
          dayId: 'day-3',
          title: 'Lunch in Sapa Town',
          startTime: '13:30',
          endTime: '14:30',
          cost: 120000,
          category: 'Food',
          order: 3,
        },
        {
          id: 'act-17',
          dayId: 'day-3',
          title: 'Check-out & Depart',
          startTime: '15:00',
          endTime: '16:00',
          cost: 0,
          category: 'Travel',
          order: 4,
        },
      ],
      transports: [
        // Day 1 transports
        {
          id: 'trans-1',
          dayId: 'day-1',
          fromActivityId: 'act-1',
          toActivityId: 'act-2',
          mode: 'walk',
          distanceKm: 1.2,
          durationMin: 18,
          cost: 0,
          departTime: '09:00',
          arriveTime: '09:18',
        },
        {
          id: 'trans-2',
          dayId: 'day-1',
          fromActivityId: 'act-2',
          toActivityId: 'act-3',
          mode: 'walk',
          distanceKm: 0.8,
          durationMin: 12,
          cost: 0,
          departTime: '11:00',
          arriveTime: '11:12',
        },
        {
          id: 'trans-3',
          dayId: 'day-1',
          fromActivityId: 'act-3',
          toActivityId: 'act-4',
          mode: 'taxi',
          distanceKm: 3.5,
          durationMin: 15,
          cost: 50000,
          departTime: '13:00',
          arriveTime: '13:15',
          notes: 'Grab taxi',
        },
        {
          id: 'trans-4',
          dayId: 'day-1',
          fromActivityId: 'act-4',
          toActivityId: 'act-5',
          mode: 'taxi',
          distanceKm: 4.2,
          durationMin: 20,
          cost: 60000,
          departTime: '19:00',
          arriveTime: '19:20',
        },
        {
          id: 'trans-5',
          dayId: 'day-1',
          mode: 'train',
          distanceKm: 296,
          durationMin: 540,
          cost: 400000,
          departTime: '21:00',
          arriveTime: '06:00',
          notes: 'Overnight sleeper train Hanoi → Lao Cai',
          provider: 'Vietnam Railways',
        },
        // Day 2 transports
        {
          id: 'trans-6',
          dayId: 'day-2',
          mode: 'bus',
          distanceKm: 38,
          durationMin: 90,
          cost: 50000,
          departTime: '06:30',
          arriveTime: '08:00',
          notes: 'Lao Cai → Sapa shuttle bus',
        },
        {
          id: 'trans-7',
          dayId: 'day-2',
          fromActivityId: 'act-8',
          toActivityId: 'act-9',
          mode: 'taxi',
          distanceKm: 2.5,
          durationMin: 10,
          cost: 30000,
          departTime: '10:00',
          arriveTime: '10:10',
        },
        {
          id: 'trans-8',
          dayId: 'day-2',
          fromActivityId: 'act-9',
          toActivityId: 'act-10',
          mode: 'walk',
          distanceKm: 1.5,
          durationMin: 22,
          cost: 0,
          departTime: '14:00',
          arriveTime: '14:22',
        },
        {
          id: 'trans-9',
          dayId: 'day-2',
          fromActivityId: 'act-10',
          toActivityId: 'act-11',
          mode: 'walk',
          distanceKm: 0.6,
          durationMin: 9,
          cost: 0,
          departTime: '15:30',
          arriveTime: '15:39',
        },
        {
          id: 'trans-10',
          dayId: 'day-2',
          fromActivityId: 'act-11',
          toActivityId: 'act-12',
          mode: 'walk',
          distanceKm: 0.4,
          durationMin: 6,
          cost: 0,
          departTime: '18:00',
          arriveTime: '18:06',
        },
        // Day 3 transports
        {
          id: 'trans-11',
          dayId: 'day-3',
          mode: 'taxi',
          distanceKm: 3.0,
          durationMin: 12,
          cost: 40000,
          departTime: '06:30',
          arriveTime: '06:42',
          notes: 'Hotel → Cable car station',
        },
        {
          id: 'trans-12',
          dayId: 'day-3',
          fromActivityId: 'act-15',
          toActivityId: 'act-16',
          mode: 'taxi',
          distanceKm: 2.8,
          durationMin: 10,
          cost: 35000,
          departTime: '13:00',
          arriveTime: '13:10',
        },
      ],
    },
  ],
}

async function seed() {
  console.log('🌱 Seeding database...')

  try {
    await writeJson('trips.json', sampleTrip)
    console.log('✅ Successfully seeded trips.json')

    await writeJson('places_cache.json', { version: 1, items: [] })
    console.log('✅ Successfully created places_cache.json')

    await writeJson('settings.json', { version: 1, defaultCurrency: 'USD' })
    console.log('✅ Successfully created settings.json')

    console.log('\n✨ Seeding complete! You can now run: bun dev')
  } catch (error) {
    console.error('❌ Seeding failed:', error)
    process.exit(1)
  }
}

seed()
